*** Variables ***
#** Form Page Locators ***
${FORM_ROW_LIST_ITEMS_TEXT}    [data-testid^="list-item-"][data-testid$="-name"]
${FORM_ROW_LIST_ITEM_ID}    [data-testid^="list-item-"][data-testid$="-id"]
${FORM_REFRESH_BUTTON}    [data-testid="refreshButton"]

#*** Info Modal Locators ***
${PAGE2_INFO_MODAL_EMAIL}        [data-testid="info-email-value"]
${PAGE2_INFO_MODAL_OK_BUTTON}    [data-testid="info-modal-ok"]
